[package]
name = "pageserver_compaction"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[features]
default = []

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
clap = { workspace = true, features = ["string"] }
futures.workspace = true
itertools.workspace = true
once_cell.workspace = true
pageserver_api.workspace = true
pin-project-lite.workspace = true
rand.workspace = true
svg_fmt.workspace = true
tokio = { workspace = true, features = ["process", "sync", "fs", "rt", "io-util", "time"] }
tracing.workspace = true
tracing-subscriber.workspace = true
utils.workspace = true
workspace_hack.workspace = true

[dev-dependencies]
criterion.workspace = true
hex-literal.workspace = true
tokio = { workspace = true, features = ["process", "sync", "fs", "rt", "io-util", "time", "test-util"] }
