[package]
name = "storage_controller_client"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
pageserver_client.workspace = true
reqwest.workspace = true
serde.workspace = true
workspace_hack = { version = "0.1", path = "../../workspace_hack" }
