name: Report Workflow Stats

on:
  workflow_run:
    workflows:
    - Add `external` label to issues and PRs created by external users
    - Benchmarking
    - Build and Test
    - Build and Test Locally
    - Build build-tools image
    - Check Permissions
    - Check neon with extra platform builds
    - Cloud Regression Test
    - Create Release Branch
    - Handle `approved-for-ci-run` label
    - Lint GitHub Workflows
    - Notify Slack channel about upcoming release
    - Periodic pagebench performance test on dedicated EC2 machine in eu-central-1 region
    - Pin build-tools image
    - Prepare benchmarking databases by restoring dumps
    - Push images to ACR
    - Test Postgres client libraries
    - Trigger E2E Tests
    - cleanup caches by a branch
    - Pre-merge checks
    types: [completed]

jobs:
  gh-workflow-stats:
    name: Github Workflow Stats
    runs-on: ubuntu-22.04
    permissions:
      actions: read
    steps:
    - name: Export GH Workflow Stats
      uses: neondatabase/gh-workflow-stats-action@v0.1.4
      with:
        DB_URI: ${{ secrets.GH_REPORT_STATS_DB_RW_CONNSTR }}
        DB_TABLE: "gh_workflow_stats_neon"
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_RUN_ID: ${{ github.event.workflow_run.id }}
